name: vayu_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.10.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  dio: ^5.3.0
  fl_chart: ^1.1.1
  google_fonts: ^6.3.2
  shared_preferences: ^2.1.5
  animations: ^2.0.6
  flutter_svg: ^2.0.7

  firebase_core: ^4.2.1
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.1.0
  google_sign_in: ^6.1.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpeg
